config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :obras do
    get 'obra_documents/index', :path => 'docs', :as => 'docs'
    get 'obra_boletos/index', :path => 'boletos', :as => 'boletos'
    get 'acompanhamento/index', :path => 'acompanhamento', :as => 'acompanhamento'
    resources :galeria
    resources :reports
  end
    devise_for :users 
    root 'plainpage#index'

end

app/models/boleto.rb
class Boleto < ActiveRecord::Base
    belongs_to :obra
    has_attached_file :fatura
    validates_attachment :fatura, :content_type => { :content_type => [  /\Aimage\/.*\z/, %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)] }
end

app/models/clima.rb
class Clima < ActiveRecord::Base
    has_many :reports
end

app/models/controle_de_obra.rb
class ControleDeObra < ActiveRecord::Base
  belongs_to :obra
  
end

app/models/documento.rb
class Documento < ActiveRecord::Base
    belongs_to :obra
    has_attached_file :document
    validates_attachment :document, :content_type => { :content_type => [  /\Aimage\/.*\z/, %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)] }
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
    belongs_to :obra
    belongs_to :function
    belongs_to :report
end

app/models/function.rb
class Function < ActiveRecord::Base
  has_many :funcionarios
end

app/models/galerium.rb
class Galerium < ActiveRecord::Base
    belongs_to :obra
    has_many :images, :dependent => :destroy
    accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/image.rb
class Image < ActiveRecord::Base
    belongs_to :galeria
    has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :foto, content_type: /\Aimage\/.*\z/
end

app/models/obra.rb
class Obra < ActiveRecord::Base
    belongs_to :user
    has_many :documentos
    has_many :boletos
    has_many :controle_de_obras
    has_many :galeria
    has_many :funcionarios
    has_many :reports
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :clima
  belongs_to :obra
  has_many :funcionarios
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :obras
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "avatar.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/obras_controller.rb
class ObrasController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_obra, only: [:show, :edit, :update, :destroy]

  # GET /obras
  # GET /obras.json
  def index
    @obras = Obra.all
  end

  # GET /obras/1
  # GET /obras/1.json
  def show
  end

  # GET /obras/new
  def new
    #@obra = current_user.obras.build
    @obra = Obra.new
  end

  # GET /obras/1/edit
  def edit
  end

  # POST /obras
  # POST /obras.json
  def create
    #@obra = current_user.obras.build(obra_params)
    @obra = Obra.new(obra_params)

    respond_to do |format|
      if @obra.save
        format.html { redirect_to @obra, notice: 'Obra was successfully created.' }
        format.json { render :show, status: :created, location: @obra }
      else
        format.html { render :new }
        format.json { render json: @obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /obras/1
  # PATCH/PUT /obras/1.json
  def update
    respond_to do |format|
      if @obra.update(obra_params)

        format.html { redirect_to @obra, notice: 'Obra was successfully updated.' }
        format.json { render :show, status: :ok, location: @obra }
      else
        format.html { render :edit }
        format.json { render json: @obra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /obras/1
  # DELETE /obras/1.json
  def destroy
    @obra.destroy
    respond_to do |format|
      format.html { redirect_to obras_url, notice: 'Obra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_obra
      @obra = Obra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def obra_params
      params.require(:obra).permit(:name, :locale, :start_date, :description, :image, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def to_reais(amount)
    if (amount.to_f < 0)
      number_to_currency(amount.abs, :precision => 0, :format => "-%u%n")
    else
      number_to_currency(amount, :format => "%u %n", :separator => ",", :delimiter => ".", :unit => "R$")
    end
    end   
end

app/helpers/boletos_helper.rb
module BoletosHelper
end

app/helpers/climas_helper.rb
module ClimasHelper
end

app/helpers/documentos_helper.rb
module DocumentosHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/galeria_helper.rb
module GaleriaHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/obra_boleto_helper.rb
module ObraBoletoHelper
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/obras/_form.html.erb
<%= form_for @obra, html: { multipart: true } do |f| %>
  <% if @obra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@obra.errors.count, "error") %> prohibited this obra from being saved:</h2>

      <ul>
      <% @obra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @obra.image %>
    <%= image_tag @obra.image.url(:medium) %>
  <% end %>
  <div class="field">
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
  <%= f.label :user %><br>
  <%= f.collection_select :user_id, User.all, :id, :email, {prompt: "Selecione um usuario"}, {class: "form-control"} %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :locale %><br>
    <%= f.text_field :locale, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="ln_solid"></div>
  <div class="actions">
    <%= f.submit "Criar Obra", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/obras/edit.html.erb
<h1>Editing Obra</h1>

<%= render 'form' %>

<%= link_to 'Show', @obra %> |
<%= link_to 'Back', obras_path %>

app/views/obras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Obras</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Locale</th>
      <th>Start date</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @obras.each do |obra| %>
      <tr>
        <td><%= obra.name %></td>
        <td><%= obra.locale %></td>
        <td><%= obra.start_date %></td>
        <td><%= obra.description %></td>
        <td><%= obra.user.email %></td>
        <td><%= link_to 'Show', obra %></td>
        <td><%= link_to 'Edit', edit_obra_path(obra) %></td>
        <td><%= link_to 'Destroy', obra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Obra', new_obra_path %>

app/views/obras/new.html.erb
<h1>New Obra</h1>

<%= render 'form' %>

<%= link_to 'Back', obras_path %>

app/views/obras/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Obra: <%= @obra.name %></h2>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <br>
      <div class="row">
        <div class="col-md-3 col-sm-3 col-xs-12">
          <%= link_to obra_acompanhamento_path(@obra), class: "btn btn-app acompanhamento" do %>
              <i class="fa fa-line-chart"></i> Acompanhamento
          <% end %>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-12">
          <%= link_to obra_galeria_path(@obra), class: "btn btn-app galeria" do %>
              <i class="fa fa-photo"></i> Galeria
          <% end %>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-12">
          <%= link_to obra_boletos_path(@obra), class: "btn btn-app pagamento" do %>
              <i class="fa fa-credit-card"></i> Pagamentos
          <% end %>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-12">
          <%= link_to obra_docs_path(@obra), class: "btn btn-app documento" do %>
              <i class="fa fa-file"></i> Documentos
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>