config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :obras do
    get 'obra_documents/index', :path => 'docs', :as => 'docs'
    get 'obra_boletos/index', :path => 'boletos', :as => 'boletos'
    get 'acompanhamento/index', :path => 'acompanhamento', :as => 'acompanhamento'
    resources :galeria
    resources :reports
  end
    devise_for :users 
    root 'plainpage#index'

end

app/models/boleto.rb
class Boleto < ActiveRecord::Base
    belongs_to :obra
    has_attached_file :fatura
    validates_attachment :fatura, :content_type => { :content_type => [  /\Aimage\/.*\z/, %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)] }
end

app/models/clima.rb
class Clima < ActiveRecord::Base
    has_many :reports
end

app/models/controle_de_obra.rb
class ControleDeObra < ActiveRecord::Base
  belongs_to :obra
  
end

app/models/documento.rb
class Documento < ActiveRecord::Base
    belongs_to :obra
    has_attached_file :document
    validates_attachment :document, :content_type => { :content_type => [  /\Aimage\/.*\z/, %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)] }
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
    belongs_to :obra
    belongs_to :function
    belongs_to :report
end

app/models/function.rb
class Function < ActiveRecord::Base
  has_many :funcionarios
end

app/models/galerium.rb
class Galerium < ActiveRecord::Base
    belongs_to :obra
    has_many :images, :dependent => :destroy
    accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/image.rb
class Image < ActiveRecord::Base
    belongs_to :galeria
    has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :foto, content_type: /\Aimage\/.*\z/
end

app/models/obra.rb
class Obra < ActiveRecord::Base
    belongs_to :user
    has_many :documentos
    has_many :boletos
    has_many :controle_de_obras
    has_many :galeria
    has_many :funcionarios
    has_many :reports
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :clima
  belongs_to :obra
  has_many :funcionarios
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :obras
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "avatar.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/boletos_controller.rb
class BoletosController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_boleto, only: [:show, :edit, :update, :destroy]

  # GET /boletos
  # GET /boletos.json
  def index
    @boletos = Boleto.all
  end

  # GET /boletos/1
  # GET /boletos/1.json
  def show
  end

  # GET /boletos/new
  def new
    @boleto = Boleto.new
  end

  # GET /boletos/1/edit
  def edit
    @obra = @boleto.obra.id
  end

  # POST /boletos
  # POST /boletos.json
  def create
    @boleto = Boleto.new(boleto_params)

    respond_to do |format|
      if @boleto.save
        format.html { redirect_to @boleto, notice: 'Boleto was successfully created.' }
        format.json { render :show, status: :created, location: @boleto }
      else
        format.html { render :new }
        format.json { render json: @boleto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boletos/1
  # PATCH/PUT /boletos/1.json
  def update
    respond_to do |format|
      if @boleto.update(boleto_params)
        format.html { redirect_to @boleto, notice: 'Boleto was successfully updated.' }
        format.json { render :show, status: :ok, location: @boleto }
      else
        format.html { render :edit }
        format.json { render json: @boleto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boletos/1
  # DELETE /boletos/1.json
  def destroy
    @boleto.destroy
    respond_to do |format|
      format.html { redirect_to boletos_url, notice: 'Boleto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boleto
      @boleto = Boleto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boleto_params
      params.require(:boleto).permit(:preco, :vencimento, :descricao, :parcelas, :situacao, :fatura, :obra_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def to_reais(amount)
    if (amount.to_f < 0)
      number_to_currency(amount.abs, :precision => 0, :format => "-%u%n")
    else
      number_to_currency(amount, :format => "%u %n", :separator => ",", :delimiter => ".", :unit => "R$")
    end
    end   
end

app/helpers/boletos_helper.rb
module BoletosHelper
end

app/helpers/climas_helper.rb
module ClimasHelper
end

app/helpers/documentos_helper.rb
module DocumentosHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/galeria_helper.rb
module GaleriaHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/obra_boleto_helper.rb
module ObraBoletoHelper
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/boletos/_form.html.erb
<%= form_for @boleto, html: { multipart: true } do |f| %>
  <% if @boleto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boleto.errors.count, "error") %> prohibited this boleto from being saved:</h2>

      <ul>
      <% @boleto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :preco %><br>
    <%= f.text_field :preco, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label :vencimento %><br>
    <%= f.date_select :vencimento, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label :parcelas %><br>
    <%= f.number_field :parcelas, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :fatura %><br>
    <%= f.file_field :fatura %>
  </div>  
  <div class="form-group">
    <%= f.label :obra %><br>
    <%= f.collection_select :obra_id, Obra.all, :id, :name, {prompt: "Selecione uma obra"}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :situacao, "Boleto pago?" %>
    <%= f.check_box :situacao %>
  </div>
  <div class="actions">
    <%= f.submit "Gerar Boleto", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/boletos/edit.html.erb
<h1>Editing Boleto</h1>

<%= render 'form' %>

<%= link_to 'Show', @boleto %> |
<%= link_to 'Back', obra_boletos_path(@obra) %>

app/views/boletos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boletos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Preco</th>
      <th>Vencimento</th>
      <th>Descricao</th>
      <th>Parcelas</th>
      <th>Situacao</th>
      <th colspan="3">Imprimir</th>
    </tr>
  </thead>

  <tbody>
    <% @boletos.each do |boleto| %>
      <tr>
        <td><%= boleto.preco %></td>
        <td><%= boleto.vencimento %></td>
        <td><%= boleto.descricao %></td>
        <td><%= boleto.parcelas %></td>
        <td><%= boleto.situacao %></td>
        <td><%= link_to 'Show', boleto %></td>
        <td><%= link_to 'Edit', edit_boleto_path(boleto) %></td>
        <td><%= link_to 'Destroy', boleto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

  </tbody>
      <% end %>
</table>

<br>

<%= link_to 'New Boleto', new_boleto_path %>

app/views/boletos/new.html.erb
<h1>New Boleto</h1>

<%= render 'form' %>

<%= link_to 'Back', boletos_path %>

app/views/boletos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Preco:</strong>
  <%= @boleto.preco %>
</p>

<p>
  <strong>Vencimento:</strong>
  <%= @boleto.vencimento %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @boleto.descricao %>
</p>

<p>
  <strong>Parcelas:</strong>
  <%= @boleto.parcelas %>
</p>

<p>
  <strong>Situacao:</strong>
  <%= @boleto.situacao %>
</p>

<%= link_to 'Edit', edit_boleto_path(@boleto) %> |
<%= link_to 'Back', boletos_path %>