config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :obras do
    get 'obra_documents/index', :path => 'docs', :as => 'docs'
    get 'obra_boletos/index', :path => 'boletos', :as => 'boletos'
    get 'acompanhamento/index', :path => 'acompanhamento', :as => 'acompanhamento'
    resources :galeria
    resources :reports
  end
    devise_for :users 
    root 'plainpage#index'

end

app/models/boleto.rb
class Boleto < ActiveRecord::Base
    belongs_to :obra
    has_attached_file :fatura
    validates_attachment :fatura, :content_type => { :content_type => [  /\Aimage\/.*\z/, %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)] }
end

app/models/clima.rb
class Clima < ActiveRecord::Base
    has_many :reports
end

app/models/controle_de_obra.rb
class ControleDeObra < ActiveRecord::Base
  belongs_to :obra
  
end

app/models/documento.rb
class Documento < ActiveRecord::Base
    belongs_to :obra
    has_attached_file :document
    validates_attachment :document, :content_type => { :content_type => [  /\Aimage\/.*\z/, %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)] }
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
    belongs_to :obra
    belongs_to :function
    belongs_to :report
end

app/models/function.rb
class Function < ActiveRecord::Base
  has_many :funcionarios
end

app/models/galerium.rb
class Galerium < ActiveRecord::Base
    belongs_to :obra
    has_many :images, :dependent => :destroy
    accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/image.rb
class Image < ActiveRecord::Base
    belongs_to :galeria
    has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :foto, content_type: /\Aimage\/.*\z/
end

app/models/obra.rb
class Obra < ActiveRecord::Base
    belongs_to :user
    has_many :documentos
    has_many :boletos
    has_many :controle_de_obras
    has_many :galeria
    has_many :funcionarios
    has_many :reports
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :clima
  belongs_to :obra
  has_many :funcionarios
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :obras
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "avatar.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/galeria_controller.rb
class GaleriaController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_galerium, only: [:show, :edit, :update, :destroy]

  # GET /galeria
  # GET /galeria.json
  def index
    if params[:obra_id].present?
    @obra = Obra.find(params[:obra_id])
    end
    @galeria = Galerium.all
  end

  # GET /galeria/1
  # GET /galeria/1.json
  def show
  end

  # GET /galeria/new
  def new
    @galerium = Galerium.new
  end

  # GET /galeria/1/edit
  def edit
  end

  # POST /galeria
  # POST /galeria.json
  def create
    @galerium = Galerium.new(galerium_params)
    
    respond_to do |format|
      if @galerium.save
        
        if params[:fotos]
          params[:fotos].each { |image|
            @galerium.images.create(foto: image)
          }
        end
        format.html { redirect_to @galerium, notice: 'Galerium was successfully created.' }
        format.json { render :show, status: :created, location: @galerium }
      else
        format.html { render :new }
        format.json { render json: @galerium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galeria/1
  # PATCH/PUT /galeria/1.json
  def update
    respond_to do |format|
      if @galerium.update(galerium_params)
        
        if params[:fotos]
          params[:fotos].each { |image|
            @galerium.images.create(foto: image)
          }
        end
        format.html { redirect_to @galerium, notice: 'Galerium was successfully updated.' }
        format.json { render :show, status: :ok, location: @galerium }
      else
        format.html { render :edit }
        format.json { render json: @galerium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galeria/1
  # DELETE /galeria/1.json
  def destroy
    @galerium.destroy
    respond_to do |format|
      format.html { redirect_to galeria_url, notice: 'Galerium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_galerium
      @galerium = Galerium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def galerium_params
      params.require(:galerium).permit(:name, :description, :obra_id, :fotos, images_attributes: [:id, :_destroy])
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def to_reais(amount)
    if (amount.to_f < 0)
      number_to_currency(amount.abs, :precision => 0, :format => "-%u%n")
    else
      number_to_currency(amount, :format => "%u %n", :separator => ",", :delimiter => ".", :unit => "R$")
    end
    end   
end

app/helpers/boletos_helper.rb
module BoletosHelper
end

app/helpers/climas_helper.rb
module ClimasHelper
end

app/helpers/documentos_helper.rb
module DocumentosHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/galeria_helper.rb
module GaleriaHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/galeria/_form.html.erb
<%= form_for @galerium, html: { multipart: true } do |f| %>
  <% if @galerium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@galerium.errors.count, "error") %> prohibited this galerium from being saved:</h2>

      <ul>
      <% @galerium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, {class: "form-control"} %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, {class: "form-control"} %>
  </div>  
  <div class="form-group">
    <%= f.label :obra %><br>
    <%= f.collection_select :obra_id, Obra.all, :id, :name, {prompt: "Selecione uma obra"}, {class: "form-control"} %>
  </div>
  <div class="field">
    <%= f.label :images %>
    <div class="controls">
    <% if @galerium.images %>
      <% @galerium.images.each do |image| %>
        <%= image_tag image.foto.url(:thumb) %>
      <% end %>
    <% end %>
      <%= file_field_tag "fotos[]", type: :file, multiple: true, class: 'form-control' %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galeria/edit.html.erb
<h1>Editing Galerium</h1>

<%= render 'form' %>

<%= link_to 'Show', @galerium %> |
<%= link_to 'Back', galeria_path %>

app/views/galeria/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Suas Fotos</h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div class="row">
          <% @obra.galeria.each do |galeria| %>
            <div class="col-md-55">
              <div class="galeriathumb thumbnail">
                <div class="image view view-first">
                  <% if !galeria.images.blank? %>
                  <%= link_to image_tag(galeria.images.first.foto.url(:medium))  %>
                  <% end %>
                  <%= link_to polymorphic_path([@obra, galeria]), data: { no_turbolink: true }  do %>
                  <div class="mask">
                    <p>Clique para ver as imagens.</p>
                  </div>
                </div>
                  <div class="caption">
                    <strong><%= galeria.name %></strong>
                    <p><%= truncate(galeria.description, :length => 25) %></p>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        
        <div class="row">
        <%= link_to "Voltar", obra_path(@obra), class: "btn btn-info" %>
        </div>
    </div>
  </div>
</div>

app/views/galeria/new.html.erb
<h1>New Galerium</h1>

<%= render 'form' %>

<%= link_to 'Back', galeria_path %>

app/views/galeria/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>
          <%= @galerium.name %>
          <br>
          <small>
            <%= @galerium.description %>
          </small>
        </h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div class="row">
          <% @galerium.images.each do |image| %>
          <div class="col-md-55">
            <%= link_to image.foto.url, class: "fancybox thumbnail galeriathumb ", :rel => 'group' do %>
            <%= image_tag image.foto.url(:medium) %>
            <% end %>
            </div>
          <% end %>
          
        </div>
        <div class="row">
        <%= link_to "Voltar", obra_galeria_path, class: "btn btn-info" %>
        </div>
    </div>
  </div>
</div>