config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :obras do
    get 'obra_documents/index', :path => 'docs', :as => 'docs'
    get 'obra_boletos/index', :path => 'boletos', :as => 'boletos'
    get 'acompanhamento/index', :path => 'acompanhamento', :as => 'acompanhamento'
    resources :galeria
    resources :reports
  end
    devise_for :users 
    root 'plainpage#index'

end

app/models/boleto.rb
class Boleto < ActiveRecord::Base
    belongs_to :obra
    has_attached_file :fatura
    validates_attachment :fatura, :content_type => { :content_type => [  /\Aimage\/.*\z/, %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)] }
end

app/models/clima.rb
class Clima < ActiveRecord::Base
    has_many :reports
end

app/models/controle_de_obra.rb
class ControleDeObra < ActiveRecord::Base
  belongs_to :obra
  
end

app/models/documento.rb
class Documento < ActiveRecord::Base
    belongs_to :obra
    has_attached_file :document
    validates_attachment :document, :content_type => { :content_type => [  /\Aimage\/.*\z/, %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)] }
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
    belongs_to :obra
    belongs_to :function
    belongs_to :report
end

app/models/function.rb
class Function < ActiveRecord::Base
  has_many :funcionarios
end

app/models/galerium.rb
class Galerium < ActiveRecord::Base
    belongs_to :obra
    has_many :images, :dependent => :destroy
    accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/image.rb
class Image < ActiveRecord::Base
    belongs_to :galeria
    has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :foto, content_type: /\Aimage\/.*\z/
end

app/models/obra.rb
class Obra < ActiveRecord::Base
    belongs_to :user
    has_many :documentos
    has_many :boletos
    has_many :controle_de_obras
    has_many :galeria
    has_many :funcionarios
    has_many :reports
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :clima
  belongs_to :obra
  has_many :funcionarios
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :obras
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "avatar.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    if params[:obra_id].present?
      @obra = Obra.find(params[:obra_id])
      @reports = @obra.reports.sort { |a,b| b.created_at <=> a.created_at } 
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ReportPdf.new(@report, view_context)
        send_data pdf.render, filename: "RDO Nº #{@report.id}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:data, :clima_id, :tarefas, :ocorrencias, :obra_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def to_reais(amount)
    if (amount.to_f < 0)
      number_to_currency(amount.abs, :precision => 0, :format => "-%u%n")
    else
      number_to_currency(amount, :format => "%u %n", :separator => ",", :delimiter => ".", :unit => "R$")
    end
    end   
end

app/helpers/boletos_helper.rb
module BoletosHelper
end

app/helpers/climas_helper.rb
module ClimasHelper
end

app/helpers/documentos_helper.rb
module DocumentosHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/galeria_helper.rb
module GaleriaHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/obra_boleto_helper.rb
module ObraBoletoHelper
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :clima_id %><br>
    <%= f.text_field :clima_id %>
  </div>
  <div class="field">
    <%= f.label :tarefas %><br>
    <%= f.text_area :tarefas %>
  </div>
  <div class="field">
    <%= f.label :ocorrencias %><br>
    <%= f.text_area :ocorrencias %>
  </div>
  <div class="field">
    <%= f.label :obra_id %><br>
    <%= f.text_field :obra_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Meus Relatórios de Obra</h2>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <!-- start project list -->
      <table class="table table-bordered projects">
        <thead>
          <tr>
            <th>Data</th>
            <th>RDO Nº</th>
            <th></th>
          </tr>
        </thead>
      
        <tbody>
          <% @reports.each do |report| %>
            <tr>
              <td><%= report.data.strftime("%d / %m / %Y") if !report.data.blank? %></td>
              <td><%= report.id %></td>
              <td><%= link_to "Ver", obra_report_path(report, report.id, format:"pdf") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
        <%= link_to "Voltar", obra_path(@obra), class: "btn btn-info" %>
      </div>
    </div>
</div>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @report.data %>
</p>

<p>
  <strong>Clima:</strong>
  <%= @report.clima %>
</p>

<p>
  <strong>Tarefas:</strong>
  <%= @report.tarefas %>
</p>

<p>
  <strong>Ocorrencias:</strong>
  <%= @report.ocorrencias %>
</p>

<p>
  <strong>Obra:</strong>
  <%= @report.obra %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>